lsi: false
theme: jekyll-theme-dinky
safe: true
source: NLP_Capstone.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
